name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - name: Checkout source code
      uses: actions/checkout@master

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@master
      with:
        node-version: ${{ matrix.node-version }}

    - name: Cache node_modules
      uses: actions/cache@master
      with:
        path: node_modules
        key: ${{runner.OS}}-build-${{hashFiles('**/yarn.lock')}}
        restore-keys: |
          ${{ runner.OS }}-build-${{ runner.OS }}-

    - name: Install dependencies
      run: yarn install --prod --pure-lockfile

    - name: Test unit
      run: yarn test

    - name: Build page
      run: yarn build
      env:
        NODE_ENV: production

    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
